import "@/styles/globals.css";
import FirebaseProvider from "../lib/authContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <FirebaseProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </FirebaseProvider>
  );
}
