import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import { ReactNode } from "react";
import SiteLayout from "@/layout";
import { twMerge } from "tailwind-merge";
import { NextAuthProvider } from "@/components/NextAuth/NextAuth";
import Script from "next/script";

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
	display: 'swap',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	                                   children,
                                   }: {
	children: ReactNode
}) {
	return (
		<html lang="en">
		<body className={twMerge(
			'max-h-screen w-full overflow-auto bg-white text-gray-600 antialiased dark:bg-gray-900 dark:text-gray-400 font-sans',
			inter.variable,
		)}>
		<Script src="https://accounts.google.com/gsi/client" />
		<NextAuthProvider>
			<SiteLayout>
				{children}
			</SiteLayout>
		</NextAuthProvider>
		</body>
		</html>
	)
}
