name: Next build-deploy

on:
  push:
    branches: ["main"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      # a standard step for GitHub actions on Node
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          # update the Node version to meet your needs
          node-version: 18
          cache: npm

      - name: Build
        run: |
          npm ci
          npm run deploy
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          NEXT_PUBLIC_FIREBASE_ADMIN_TYPE: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_TYPE }}
          NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATE_KEY_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATE_KEY_ID }}
          NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATE_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATE_KEY }}
          NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_EMAIL: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_EMAIL }}
          NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_ID }}
          NEXT_PUBLIC_FIREBASE_ADMIN_AUTH_URI: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_AUTH_URI }}
          NEXT_PUBLIC_FIREBASE_ADMIN_TOKEN_URI: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_TOKEN_URI }}
          NEXT_PUBLIC_FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL }}
          NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_X509_CERT_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_X509_CERT_URL }}

      - name: Deploy to GitHub Pages
        # uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: out
          
      # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
