name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Installing my packages
        run: npm ci

      - name: Build my App
        run: npm run build && npm run export && touch ./out/.nojekyll
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          NEXT_PUBLIC_FIREBASE_ADMIN_TYPE: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_TYPE }}
          NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATE_KEY_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATE_KEY_ID }}
          NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATE_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATE_KEY }}
          NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_EMAIL: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_EMAIL }}
          NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_ID }}
          NEXT_PUBLIC_FIREBASE_ADMIN_AUTH_URI: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_AUTH_URI }}
          NEXT_PUBLIC_FIREBASE_ADMIN_TOKEN_URI: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_TOKEN_URI }}
          NEXT_PUBLIC_FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL }}
          NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_X509_CERT_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_X509_CERT_URL }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
